[package]
name = "patchers"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = {version = "4.5.49", features = ["derive"]}
crossterm = { version = "0.29" }
ratatui = "0.29.0"
serde = "1.0.228"
